name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Start containers
      run: docker-compose -f "./docker/docker-compose.yml" up -d --build || true
    - name: Exec containers
      run: docker-compose exec python3 bash
    - name: Move to app.py directory
      run: cd opt/
    - name: Run app.py
      run: python app.py
